"""Initial Migration

Revision ID: 33d6cfeb1389
Revises: 
Create Date: 2023-07-04 09:56:08.880507

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '33d6cfeb1389'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_pokemon_id', table_name='pokemon')
    op.drop_index('ix_pokemon_name', table_name='pokemon')
    op.drop_index('ix_pokemon_wiki', table_name='pokemon')
    op.drop_table('pokemon')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('pokemon',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('name', sa.VARCHAR(), nullable=True),
    sa.Column('wiki', sa.VARCHAR(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_pokemon_wiki', 'pokemon', ['wiki'], unique=False)
    op.create_index('ix_pokemon_name', 'pokemon', ['name'], unique=False)
    op.create_index('ix_pokemon_id', 'pokemon', ['id'], unique=False)
    # ### end Alembic commands ###
